name: feather_canvas_studio
description: "FeatherCanvas Studio is a Flutter client for OpenAI-compatible image generation APIs."
publish_to: 'none'
version: 0.2.6

environment:
  sdk: ^3.11.5

dependencies:
  archive: ^4.0.9
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 9.2.4
  http: ^1.6.0
  image: ^4.8.0
  intl: any
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
